export const storeProducts = [
  {
    id: 1,
    title: "MARSHALL MATHERS FOUNDATION X DETROIT VS EVERYBODY - LONGSLEEVE",
    img: "img/product-1alt.png",
    imgalt:'img/product-1.png',
    price: 45,
    company: "GOOGLE",
    info:"THE MARSHALL MATHERS FOUNDATION X DETROIT VS. EVERYBODY FOR THE VERSES PROJECT. EXCLUSIVE TO THE EMINEM STORE, THE MARSHALL MATHERS FOUNDATION LINKS UP WITH DETROIT VS. EVERYBODY TO REVIVE THEIR SHADY VS. EVERYBODY COLLAB ON CARHARTT GOODS TO RAISE MONEY FOR THE VERSES PROJECT.PRINTED ON A CARHARTT LONGSLEEVE. SPECIAL THANKS TO DETROIT VS EVERYBODY AND TOMMEY WALKER JR. AN OFFICIALLY LICENSED VS EVERYBODY® PRODUCT.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 2,
    title: "MARSHALL MATHERS FOUNDATION X DETROIT VS EVERYBODY - HOODIE",
    img: "img/product-2alt.png",
    imgalt:'img/product-2.png',
    price: 70,
    company: "SAMSUNG",
    info:"THE MARSHALL MATHERS FOUNDATION X DETROIT VS. EVERYBODY FOR THE VERSES PROJECT. EXCLUSIVE TO THE EMINEM STORE, THE MARSHALL MATHERS FOUNDATION LINKS UP WITH DETROIT VS. EVERYBODY TO REVIVE THEIR SHADY VS. EVERYBODY COLLAB ON CARHARTT GOODS TO RAISE MONEY FOR THE VERSES PROJECT.PRINTED ON A CARHARTT LONGSLEEVE. SPECIAL THANKS TO DETROIT VS EVERYBODY AND TOMMEY WALKER JR. AN OFFICIALLY LICENSED VS EVERYBODY® PRODUCT.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 3,
    title: "MARSHALL MATHERS FOUNDATION X DETROIT VS EVERYBODY - ZIP UP HOODIE",
    img: "img/product-3.png",
    imgalt:'img/product-1alt.png',
    price: 70,
    company: "htc",
    info:"THE MARSHALL MATHERS FOUNDATION X DETROIT VS. EVERYBODY FOR THE VERSES PROJECT. EXCLUSIVE TO THE EMINEM STORE, THE MARSHALL MATHERS FOUNDATION LINKS UP WITH DETROIT VS. EVERYBODY TO REVIVE THEIR SHADY VS. EVERYBODY COLLAB ON CARHARTT GOODS TO RAISE MONEY FOR THE VERSES PROJECT.PRINTED ON A CARHARTT LONGSLEEVE. SPECIAL THANKS TO DETROIT VS EVERYBODY AND TOMMEY WALKER JR. AN OFFICIALLY LICENSED VS EVERYBODY® PRODUCT.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 4,
    title: "KAMIKAZE GREEN HOODIE",
    img: "img/product-4.png",
    imgalt:'img/product-4alt.png',
    price: 60,
    company: "htc",
    info:"THE MARSHALL MATHERS FOUNDATION X DETROIT VS. EVERYBODY FOR THE VERSES PROJECT. EXCLUSIVE TO THE EMINEM STORE, THE MARSHALL MATHERS FOUNDATION LINKS UP WITH DETROIT VS. EVERYBODY TO REVIVE THEIR SHADY VS. EVERYBODY COLLAB ON CARHARTT GOODS TO RAISE MONEY FOR THE VERSES PROJECT.PRINTED ON A CARHARTT LONGSLEEVE. SPECIAL THANKS TO DETROIT VS EVERYBODY AND TOMMEY WALKER JR. AN OFFICIALLY LICENSED VS EVERYBODY® PRODUCT.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "PLANE CREWNECK",
    img: "img/product-5.png",
    imgalt:'img/product-5alt.png',
    price: 45,
    company: "htc",
    info:"THE MARSHALL MATHERS FOUNDATION X DETROIT VS. EVERYBODY FOR THE VERSES PROJECT. EXCLUSIVE TO THE EMINEM STORE, THE MARSHALL MATHERS FOUNDATION LINKS UP WITH DETROIT VS. EVERYBODY TO REVIVE THEIR SHADY VS. EVERYBODY COLLAB ON CARHARTT GOODS TO RAISE MONEY FOR THE VERSES PROJECT.PRINTED ON A CARHARTT LONGSLEEVE. SPECIAL THANKS TO DETROIT VS EVERYBODY AND TOMMEY WALKER JR. AN OFFICIALLY LICENSED VS EVERYBODY® PRODUCT.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 6,
    title: "Death Before Defeat Lightweight Black Bomber",
    img: "img/product-6.png",
    imgalt:'img/product-6alt.png',
    price: 60,
    company: "apple",
    info:"THE MARSHALL MATHERS FOUNDATION X DETROIT VS. EVERYBODY FOR THE VERSES PROJECT. EXCLUSIVE TO THE EMINEM STORE, THE MARSHALL MATHERS FOUNDATION LINKS UP WITH DETROIT VS. EVERYBODY TO REVIVE THEIR SHADY VS. EVERYBODY COLLAB ON CARHARTT GOODS TO RAISE MONEY FOR THE VERSES PROJECT.PRINTED ON A CARHARTT LONGSLEEVE. SPECIAL THANKS TO DETROIT VS EVERYBODY AND TOMMEY WALKER JR. AN OFFICIALLY LICENSED VS EVERYBODY® PRODUCT.",
    inCart: false,
    count: 0,
    total: 0
  }
];
export const detailProduct = {
  id: 1,
  title: "MARSHALL MATHERS FOUNDATION X DETROIT VS EVERYBODY - LONGSLEEVE",
  img: "img/product-1.png",
  imgalt:'img/product-1alt.png',
  price: 10,
  company: "google",
  info:"THE MARSHALL MATHERS FOUNDATION X DETROIT VS. EVERYBODY FOR THE VERSES PROJECT. EXCLUSIVE TO THE EMINEM STORE, THE MARSHALL MATHERS FOUNDATION LINKS UP WITH DETROIT VS. EVERYBODY TO REVIVE THEIR SHADY VS. EVERYBODY COLLAB ON CARHARTT GOODS TO RAISE MONEY FOR THE VERSES PROJECT.PRINTED ON A CARHARTT LONGSLEEVE. SPECIAL THANKS TO DETROIT VS EVERYBODY AND TOMMEY WALKER JR. AN OFFICIALLY LICENSED VS EVERYBODY® PRODUCT.",
  inCart: false,
  count: 0,
  total: 0
};
